### ISSUE TITLE
[Feature Request] Homing if usb disconnects midprint.

### ISSUE THREAD

**Issue by Kellwaxx11** [NuclearPhoenixx/Kobra_Neo#4]
Dear @NuclearPhoenixx 
firstly many thanks for the firmware, am using for a while now and it is amazing.

is it possible to add a functionality, to be a companion for OctoPrint, where the hotend moves away in case usb diconnected while printing, not to keep melting the plastic.
meanwhile in Octoprint while using "Power Failure Recovery" plugin, we will be able to continue the print -hopefully-.

or if you have other idea to handle such situation, its much apreciated.

Thank you in advance.

**Comment by NuclearPhoenixx** [comment]
Hi there, I had a little search online to look for a similar functionality and it looks like neither Marlin nor Octoprint have something like this. AFAIK Octoprint only allows you to run gcode after a successful manual disconnect from the printer, not a sudden accidental disconnect of the USB cable. Problem is that the host sends all the gcode so the printer doesn't know what to do when it fails. I haven't tried it yet, but what happens if you disconnect? Does it just stop in its last position powered-on?

I think this feature affects Marlin more than this repo, because that sounds like a very general function to have for all 3D printers. I don't think it's viable to code such a general function only to this firmware instead of going straight to contributing to vanilla Marlin.

Do you know of any similar functionality in Marlin or Octoprint? Maybe I've missed something, but I didn't find that much regarding host connections in the Marlin config to begin with.

**Comment by Kellwaxx11** [comment]
on accidental disconnect of the USB cable, the printer just stays on , everything tempretures and fans
and the hotend stays on its last position, melting plastic that was already printed.

I agree with you, it could be a general Marlin functionality, I didnt research if that already exists for other printers to be honest, and am not sure how quick would it be to update the official Marlin repo, thats why I asked it here.
i have more faith in custom build rather than official :)

am not aware of similar functionality other than this plugin for Octoprint, that seems to work well, **IF I GET THE CONNECTION BACK**
https://github.com/pablogventura/OctoPrint-PowerFailure

the only issue with this, is how to force octoprint to reconnect to the printer automatically
I have tried other plugins for that "PortLister" and "PSU Control" but it didnt work, at least on my side.

**Comment by NuclearPhoenixx** [comment]
Yeah sorry, but I don't think I know remotely enough to implement something like this. As of now I have only modified the config files and had a go with the menu and lcd functions and stuff like that, but nothing at the very core level of Marlin. I don't even know if the device itself is capable of detecting that a connection has failed in the first place. AFAIK host actions are done via the serial interface, so there should be a way to detect that, but not sure how that plays together with Octoprint.

Your best bet would be to open an issue in the official Marlin repo and see what people have done there: https://github.com/MarlinFirmware/Marlin/issues

Maybe that change can then be ported back here, not sure.

**Comment by NuclearPhoenixx** [comment]
Like I said, I really don't have the knowledge to do that and if I would have it, I'd look to contribute to Marlin directly. That's why I'm closing this issue now with the "won't fix" tag, sorry. Please let me know if you have any more questions.

**Comment by Kellwaxx11** [comment]
totally makes sense
thank you for replying and for the advice.
