### ISSUE TITLE
kobra neo firmware bl touch 

### ISSUE THREAD

**Issue by Rerui45** [NuclearPhoenixx/Kobra_Neo#5]
Hello, could you help me with the kobra neo firmware? I would like to flash it for bl touch, but I can’t do it, I don’t understand this very well, so I’ll be grateful if you answer

**Comment by Rerui45** [comment]
and if possible we could unlock the Russian language

**Comment by NuclearPhoenixx** [comment]
Hi there,

you can enable BLTOUCH here: https://github.com/NuclearPhoenixx/Kobra_Neo/blob/2fcd44aa9ac1e0af3dcbb41cddf4bfe4761c8040/source/Marlin/Configuration.h#L929

And change some settings here: https://github.com/NuclearPhoenixx/Kobra_Neo/blob/2fcd44aa9ac1e0af3dcbb41cddf4bfe4761c8040/source/Marlin/Configuration_adv.h#L674

Unfortunately, I wouldn't be surprised if it doesn't compile successfully since they removed a ton of other features from Marlin that aren't needed out of the box for the Neo.

As for the languages, this is fairly easy. I don't think I can add another one since there are only 5 slots, but you can remove an existing one and replace it with Russian here: https://github.com/NuclearPhoenixx/Kobra_Neo/blob/2fcd44aa9ac1e0af3dcbb41cddf4bfe4761c8040/source/Marlin/Configuration.h#L1841

**Comment by Rerui45** [comment]
Спасибо за ответ надеюсь я хоть что нибудь смогу сделать а то я уже пробовал и программу наверное не ту выбрал

**Comment by Rerui45** [comment]
hello, it's me again. My problem is that when I turn on Bl touch, it gives 207 errors.

**Comment by Rerui45** [comment]
[Новый текстовый документ.txt](https://github.com/NuclearPhoenixx/Kobra_Neo/files/14575550/default.txt)

**Comment by NuclearPhoenixx** [comment]
Just read the error message, it tells you what's wrong:

```text
Please enable only one probe option: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo."
    #error "Please enable only one probe option: PROBE_MANUALLY, SENSORLESS_PROBING, BLTOUCH, FIX_MOUNTED_PROBE, NOZZLE_AS_PROBE, TOUCH_MI_PROBE, SOLENOID_PROBE, Z_PROBE_ALLEN_KEY, Z_PROBE_SLED, or Z Servo.
```

You need to disable all the other options by commenting out. What's probably wrong is that you left `FIX_MOUNTED_PROBE` enabled, which is the default probing for the Neo. Just comment that out and try again.

Btw, you can copy and paste the debug log into a comment here. Better this way than to use txt files.

**Comment by Rerui45** [comment]
Спасибо все заработало 👍

**Comment by Rerui45** [comment]
please tell me, can I do something with the solar fan, otherwise I changed the 5012 24v 0.06a and it doesn’t work

**Comment by NuclearPhoenixx** [comment]
> Спасибо все заработало 👍

Does BLTouch actually work now? That's pretty neat, I didn't expect that.

> please tell me, can I do something with the solar fan, otherwise I changed the 5012 24v 0.06a and it doesn’t work

The "solar fan"? Do you mean like the parts fan? You're probably better off looking at the [KobraGoNeoInsights](https://github.com/1coderookie/KobraGoNeoInsights) for that.

**Comment by NuclearPhoenixx** [comment]
Looks to be resolved (stale), closing for now. If you feel like it isn't resolved, I can reopen.
