### ISSUE TITLE
Porting Marlin-H32

### ISSUE THREAD

**Issue by Alecs25** [NuclearPhoenixx/Kobra_Neo#8]
Hi There! Happened to compile with Keil, just curious. I saw the readme about that fork, and the issues with SoftwareSerial that appear missing in the latest dev.

But, i checked the old dev branches, and they all have this library. Wouldn't it possible to merge with that old branch and then merge with the latest versions? 

Hope to not bother anyone, i don't have great coding skills with hardware.
edit 1:
The branches i'm talking about:
https://github.com/shadow578/Marlin-H32/tree/old/aquila-h32
https://github.com/shadow578/Marlin-H32/tree/old/aquila-h32_merge-upstream
https://github.com/shadow578/Marlin-H32/tree/old/aquila-bugfix-2.1.x

Edit 2:
Ok i may have understood what is the problem, since it's using atmega2560 platform, which does not support LCD SPI for example.

**Comment by NuclearPhoenixx** [comment]
It's been a long time since I last worked on this so I'm not 100% sure what the problem was. I can tell you I have also tried countless times to merge vanilla Marlin with this code to make it at least somewhat maintainable and also with hopes to upgrade to a more current Marlin version. I wasted way too many hours on this, the code is absolute garbage and also the fact that we have to use Keil makes everything a lot more complicated as well ._.

**Comment by Alecs25** [comment]
Thanks for the answer. I'll try to understand better, probably can't do anything but just curious. Love to get in troubles.

Cheers!
